package com.Jessy1237.McVS;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

@SuppressWarnings("serial")
public class InputCurrentJarGUI extends JFrame{
	
	public JButton bu;
	public JTextField a;
	public JLabel bc;
	public JLabel bb;
	public JLabel ba;
	public JLabel bd;
	
	public static String text;
	public static String osName = System.getProperty("os.name").toLowerCase();
	public static String userHome = System.getProperty("user.home");
	public static File Windir = new File(userHome,
		"/AppData/roaming/.minecraft/bin");
	public static File dir = new File(userHome,
		"/Library/Application Support/minecraft/bin");
	public static File Wintxt = new File(Windir, "/.mcversion.txt");
	public static File Mactxt = new File(dir, "/mcversion.txt");
	
	public static void a(){
		InputCurrentJarGUI i = new InputCurrentJarGUI();
		i.setVisible(false);
	}
	
	public static void c(){
		if(osName.contains("win")){
			try{
			FileOutputStream out = new FileOutputStream(Wintxt);
			McVS.prop.put("jar", text);
			McVS.prop.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
			McVS.mcver();
			}catch(IOException e){
				e.printStackTrace();
			}
		}else{
			try{
			FileOutputStream out = new FileOutputStream(Mactxt);
			McVS.prop.put("jar", text);
			McVS.prop.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
			McVS.mcver();
			}catch(IOException r){
				r.printStackTrace();
			}
		}
	}
	
	public InputCurrentJarGUI(){
		this.setTitle("Minecraft Version Switcher: Input Current Jar");
		this.setSize(new Dimension(480, 220));
		this.setLocation(MouseInfo.getPointerInfo().getLocation());
		this.setResizable(false);
		this.setLayout(null);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.a = new JTextField();
		this.a.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				text = a.getText();
				setVisible(false);
				if(!text.equals("1.1") && !text.equals("1.7") && !text.equals("1.8") && !text.equals("1.0") && !text.equals("1.2")){
					int size = JarMethods.names.size() + 1;
					JarMethods.names.put("custom" + size, text);
				}
				c();
				McVS newform = new McVS();
				newform.setVisible(true);
			}
		});
		this.bu = new JButton();
		this.bu.setText("Done");
		this.bu.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				text = a.getText();
				setVisible(false);
				c();
				McVS newform = new McVS();
				newform.setVisible(true);
			}
		});
		bc = new JLabel();
		bc.setText("Minecraft Beta 1.7 = 1.7");
		bc.setBounds(160, 40, 180, 20);
		bc.setFont(new Font("Arial", Font.PLAIN, 14));
		
		bb = new JLabel();
		bb.setText("Minecraft Beta 1.8.1 = 1.8");
		bb.setFont(new Font("Arial", Font.PLAIN, 14));
		bb.setBounds(160, 60, 180, 20);
		
		ba = new JLabel();
		ba.setText("Minecraft X.X.X = X.X");
		ba.setFont(new Font("Arial", Font.PLAIN, 14));
		ba.setBounds(160, 80, 180, 20);
		
		bd = new JLabel();
		bd.setText("Enter you current Minecraft version. Custom Jars are Allowed!");
		bd.setFont(new Font("Arial", Font.PLAIN, 14));
		bd.setBounds(10, 10, 460, 20);
		
		a.setText("E.g. 1.7, 1.8, 1.0 or 1.1");
		a.setBounds(180, 115, 90, 25);
		
		bu.setBounds(185, 155, 70, 30);
		
		add(bd);
		add(bc);
		add(bb);
		add(ba);
		add(a);
		add(bu);
	}
}