package com.Jessy1237.McVS;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

public class TextMaker {

	public static String userHome = System.getProperty("user.home");
	public static File Windir = new File(userHome,
			"/AppData/roaming/.minecraft/bin");
	public static File Wintxt = new File(Windir, "/.mcversion.txt");
	public static File dir = new File(userHome,
			"/Library/Application Support/minecraft/bin");
	public static File Mactxt = new File(dir, "/mcversion.txt");
	static String osName = System.getProperty("os.name").toLowerCase();
	static TextWriter Wr;
	static Properties prop1 = new Properties();

	public TextMaker() {
		Wr = new TextWriter();
	}

	public static void txt() throws IOException {
		if (osName.contains("win")) {
			FileOutputStream out = new FileOutputStream(Wintxt);
			prop1.put("jar", null);
			prop1.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
		}else{
		FileOutputStream out = new FileOutputStream(Mactxt);
		prop1.put("jar", null);
		prop1.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
		}
	}
}
