package com.Jessy1237.McVS;

import java.io.*;

public class TextWriter {

	public static String userHome = System.getProperty("user.home");
	public static File Windir = new File(userHome, "/AppData/roaming/.minecraft/bin");
	public static File Wintxt = new File(Windir, "/.mcversion.txt");
	public static File dir = new File(userHome, "/Library/Application Support/minecraft/bin");
	public static File Mactxt = new File(dir, "/mcversion.txt");
	
	public void Wintxt18() throws IOException {
		FileOutputStream out = new FileOutputStream(Wintxt);
		McVS.prop.put("jar", "1.8");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Wintxt1() throws IOException{
		FileOutputStream out = new FileOutputStream(Wintxt);
		McVS.prop.put("jar", "1.0");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Wintxt11() throws IOException{
		FileOutputStream out = new FileOutputStream(Wintxt);
		McVS.prop.put("jar", "1.1");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Wintxt17() throws IOException {
		FileOutputStream out = new FileOutputStream(Wintxt);
		McVS.prop.put("jar", "1.7");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Mactxt18() throws IOException {
		FileOutputStream out = new FileOutputStream(Mactxt);
		McVS.prop.put("jar", "1.8");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Mactxt17() throws IOException {
		FileOutputStream out = new FileOutputStream(Mactxt);
		McVS.prop.put("jar", "1.7");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Mactxt1() throws IOException {
		FileOutputStream out = new FileOutputStream(Mactxt);
		McVS.prop.put("jar", "1.0");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
	
	public void Mactxt11() throws IOException {
		FileOutputStream out = new FileOutputStream(Mactxt);
		McVS.prop.put("jar", "1.1");
		McVS.prop.store(out, "Do Not Edit This File!");
		out.flush();
		out.close();
	}
}
