package com.Jessy1237.McVS.Management;

import java.io.*;

import com.Jessy1237.McVS.McVS;

public class TextWriter {

	public static String userHome = System.getProperty("user.home");
	public static File Windir = new File(userHome, "/AppData/roaming/.minecraft/bin");
	public static File Wintxt = new File(Windir, "/mcversion.txt");
	public static File dir = new File(userHome, "/Library/Application Support/minecraft/bin");
	public static File Mactxt = new File(dir, "/mcversion.txt");
	public static File Lindir = new File(userHome, "/.minecraft/bin");
	public static File Lintxt = new File(Lindir, "/mcversion.txt");

	public void write(String ver) throws IOException {
		if (McVS.osName.contains("win")) {
			FileOutputStream out = new FileOutputStream(Wintxt);
			McVS.prop.put("jar", ver);
			McVS.prop.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
		} else if (McVS.osName.contains("mac")) {
			FileOutputStream out = new FileOutputStream(Mactxt);
			McVS.prop.put("jar", ver);
			McVS.prop.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
		} else if (McVS.osName.contains("linux")) {
			FileOutputStream out = new FileOutputStream(Lintxt);
			McVS.prop.put("jar", ver);
			McVS.prop.store(out, "Do Not Edit This File!");
			out.flush();
			out.close();
		}
	}
}
